"""
Mock data generator - 30+ properties for demo/testing.
Must pass through complete pipeline (Tier classification + Math weighting).
Distributed across multiple administrative districts.
"""
import json
from schemas import Property
from npp_enum import NPP_ENUM

# Sample mock properties - 40 properties across different districts
MOCK_PROPERTIES = [
    # ─── Johor Bahru City ───────────────────────────────────
    Property(
        property_id="JB001",
        title="Modern Condo @ Bukit Indah",
        price=480000,
        location="Bukit Indah, Johor Bahru",
        administrative_district="johor_bahru_city",
        distance_to_mrt_km=1.5,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "playground"],
        facilities_score=0.85,
        nearby_schools=3,
        nearby_tuition_centers=2,
        nearby_malls=2,
        nearby_clinics=1,
        lifestyle_proximity_score=0.80,
        maintenance_fee_per_sqft=0.45,
        normalized_maintenance_fee=0.30,
        flood_risk="low",
        feature_tags=["no_balcony"],
        price_fit_score=0.95,
        security_score=0.90,
        transit_proximity_score=0.85,
        floor_level=15,
        facing="north",
        bedrooms=3,
        bathrooms=2,
        url="https://edgeprop.my/mock/jb001",
        source="EdgeProp.my",
        is_mock=True,
    ),
    Property(
        property_id="JB002",
        title="Luxury Apartment @ CIQ",
        price=520000,
        location="CIQ, Johor Bahru",
        administrative_district="johor_bahru_city",
        distance_to_mrt_km=0.8,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "security"],
        facilities_score=0.88,
        nearby_schools=4,
        nearby_tuition_centers=3,
        nearby_malls=3,
        nearby_clinics=2,
        lifestyle_proximity_score=0.85,
        maintenance_fee_per_sqft=0.50,
        normalized_maintenance_fee=0.35,
        flood_risk="low",
        feature_tags=[],
        price_fit_score=0.92,
        security_score=0.95,
        transit_proximity_score=0.90,
        floor_level=12,
        facing="south",
        bedrooms=4,
        bathrooms=3,
        url="https://edgeprop.my/mock/jb002",
        source="EdgeProp.my",
        is_mock=True,
    ),
    Property(
        property_id="JB003",
        title="Mid-Range Condo @ Perling",
        price=420000,
        location="Perling, Johor Bahru",
        administrative_district="johor_bahru_city",
        distance_to_mrt_km=3.2,
        is_gated_guarded=True,
        security_level="medium",
        facilities=["pool", "parking"],
        facilities_score=0.65,
        nearby_schools=2,
        nearby_tuition_centers=1,
        nearby_malls=1,
        nearby_clinics=1,
        lifestyle_proximity_score=0.60,
        maintenance_fee_per_sqft=0.35,
        normalized_maintenance_fee=0.20,
        flood_risk="low",
        feature_tags=["high_floor", "west_facing"],
        price_fit_score=0.78,
        security_score=0.70,
        transit_proximity_score=0.60,
        floor_level=18,
        facing="west",
        bedrooms=3,
        bathrooms=2,
        url="https://mudah.my/mock/jb003",
        source="Mudah.my",
        is_mock=True,
    ),
    Property(
        property_id="JB004",
        title="Budget Apartment @ Taman Daya",
        price=380000,
        location="Taman Daya, Johor Bahru",
        administrative_district="johor_bahru_city",
        distance_to_mrt_km=5.0,
        is_gated_guarded=False,
        security_level="low",
        facilities=["parking"],
        facilities_score=0.40,
        nearby_schools=1,
        nearby_tuition_centers=0,
        nearby_malls=0,
        nearby_clinics=1,
        lifestyle_proximity_score=0.45,
        maintenance_fee_per_sqft=0.25,
        normalized_maintenance_fee=0.10,
        flood_risk="medium",
        feature_tags=["no_security", "low_floor", "far_from_mrt"],
        price_fit_score=0.65,
        security_score=0.45,
        transit_proximity_score=0.40,
        floor_level=3,
        facing="east",
        bedrooms=2,
        bathrooms=1,
        url="https://propsocial.my/mock/jb004",
        source="PropSocial.my",
        is_mock=True,
    ),
    Property(
        property_id="JB005",
        title="New Launch @ Skudai Tech Park",
        price=495000,
        location="Skudai Tech Park, Skudai",
        administrative_district="skudai",
        distance_to_mrt_km=2.0,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "playground", "security"],
        facilities_score=0.90,
        nearby_schools=3,
        nearby_tuition_centers=2,
        nearby_malls=2,
        nearby_clinics=1,
        lifestyle_proximity_score=0.82,
        maintenance_fee_per_sqft=0.48,
        normalized_maintenance_fee=0.32,
        flood_risk="low",
        feature_tags=[],
        price_fit_score=0.93,
        security_score=0.92,
        transit_proximity_score=0.82,
        floor_level=8,
        facing="north",
        bedrooms=3,
        bathrooms=2,
        url="https://starproperty.my/mock/jb005",
        source="StarProperty.my",
        is_mock=True,
    ),
    Property(
        property_id="JB006",
        title="Affordable Studio @ Iskandar Puteri",
        price=350000,
        location="Iskandar Puteri, Nusajaya",
        administrative_district="iskandar_puteri",
        distance_to_mrt_km=4.5,
        is_gated_guarded=False,
        security_level="medium",
        facilities=["gym", "parking"],
        facilities_score=0.55,
        nearby_schools=1,
        nearby_tuition_centers=0,
        nearby_malls=1,
        nearby_clinics=0,
        lifestyle_proximity_score=0.50,
        maintenance_fee_per_sqft=0.28,
        normalized_maintenance_fee=0.12,
        flood_risk="low",
        feature_tags=["small_unit", "far_from_mrt"],
        price_fit_score=0.60,
        security_score=0.65,
        transit_proximity_score=0.45,
        floor_level=5,
        facing="south",
        bedrooms=1,
        bathrooms=1,
        url="https://iproperty.com.my/mock/jb006",
        source="iProperty.com.my",
        is_mock=True,
    ),

    # ─── Kuala Lumpur ───────────────────────────────────────
    Property(
        property_id="KL001",
        title="KLCC Prime Location Condo",
        price=550000,
        location="KLCC, Kuala Lumpur",
        administrative_district="kuala_lumpur_city",
        distance_to_mrt_km=0.5,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "concierge"],
        facilities_score=0.95,
        nearby_schools=3,
        nearby_tuition_centers=2,
        nearby_malls=5,
        nearby_clinics=2,
        lifestyle_proximity_score=0.95,
        maintenance_fee_per_sqft=0.65,
        normalized_maintenance_fee=0.55,
        flood_risk="low",
        feature_tags=[],
        price_fit_score=0.88,
        security_score=0.98,
        transit_proximity_score=0.98,
        floor_level=25,
        facing="north",
        bedrooms=3,
        bathrooms=2,
        url="https://edgeprop.my/mock/kl001",
        source="EdgeProp.my",
        is_mock=True,
    ),
    Property(
        property_id="KL002",
        title="Bukit Bintang Urban Residence",
        price=480000,
        location="Bukit Bintang, Kuala Lumpur",
        administrative_district="kuala_lumpur_city",
        distance_to_mrt_km=1.2,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking"],
        facilities_score=0.85,
        nearby_schools=2,
        nearby_tuition_centers=2,
        nearby_malls=4,
        nearby_clinics=2,
        lifestyle_proximity_score=0.90,
        maintenance_fee_per_sqft=0.50,
        normalized_maintenance_fee=0.35,
        flood_risk="low",
        feature_tags=["no_balcony"],
        price_fit_score=0.95,
        security_score=0.92,
        transit_proximity_score=0.92,
        floor_level=14,
        facing="east",
        bedrooms=2,
        bathrooms=1,
        url="https://mudah.my/mock/kl002",
        source="Mudah.my",
        is_mock=True,
    ),
    Property(
        property_id="KL003",
        title="Mont Kiara Luxury Towers",
        price=520000,
        location="Mont Kiara, Kuala Lumpur",
        administrative_district="mont_kiara",
        distance_to_mrt_km=2.5,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "security"],
        facilities_score=0.90,
        nearby_schools=4,
        nearby_tuition_centers=3,
        nearby_malls=2,
        nearby_clinics=1,
        lifestyle_proximity_score=0.85,
        maintenance_fee_per_sqft=0.55,
        normalized_maintenance_fee=0.40,
        flood_risk="low",
        feature_tags=[],
        price_fit_score=0.90,
        security_score=0.95,
        transit_proximity_score=0.80,
        floor_level=20,
        facing="north",
        bedrooms=4,
        bathrooms=3,
        url="https://propsocial.my/mock/kl003",
        source="PropSocial.my",
        is_mock=True,
    ),
    Property(
        property_id="KL004",
        title="Ampang Residential Complex",
        price=420000,
        location="Ampang, Kuala Lumpur",
        administrative_district="ampang",
        distance_to_mrt_km=3.0,
        is_gated_guarded=True,
        security_level="medium",
        facilities=["pool", "parking"],
        facilities_score=0.70,
        nearby_schools=2,
        nearby_tuition_centers=1,
        nearby_malls=1,
        nearby_clinics=1,
        lifestyle_proximity_score=0.65,
        maintenance_fee_per_sqft=0.40,
        normalized_maintenance_fee=0.25,
        flood_risk="low",
        feature_tags=["high_floor"],
        price_fit_score=0.78,
        security_score=0.75,
        transit_proximity_score=0.65,
        floor_level=16,
        facing="west",
        bedrooms=3,
        bathrooms=2,
        url="https://starproperty.my/mock/kl004",
        source="StarProperty.my",
        is_mock=True,
    ),
    Property(
        property_id="KL005",
        title="Budget Studio @ Cheras",
        price=360000,
        location="Cheras, Kuala Lumpur",
        administrative_district="cheras",
        distance_to_mrt_km=4.2,
        is_gated_guarded=False,
        security_level="low",
        facilities=["parking"],
        facilities_score=0.45,
        nearby_schools=1,
        nearby_tuition_centers=0,
        nearby_malls=0,
        nearby_clinics=1,
        lifestyle_proximity_score=0.50,
        maintenance_fee_per_sqft=0.30,
        normalized_maintenance_fee=0.15,
        flood_risk="medium",
        feature_tags=["no_security", "small_unit", "far_from_mrt"],
        price_fit_score=0.62,
        security_score=0.50,
        transit_proximity_score=0.50,
        floor_level=4,
        facing="south",
        bedrooms=1,
        bathrooms=1,
        url="https://iproperty.com.my/mock/kl005",
        source="iProperty.com.my",
        is_mock=True,
    ),

    # ─── Petaling Jaya ──────────────────────────────────────
    Property(
        property_id="PJ001",
        title="Petaling Jaya Prime Condo",
        price=500000,
        location="PJ, Selangor",
        administrative_district="petaling_jaya",
        distance_to_mrt_km=1.8,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "security"],
        facilities_score=0.88,
        nearby_schools=3,
        nearby_tuition_centers=2,
        nearby_malls=3,
        nearby_clinics=2,
        lifestyle_proximity_score=0.85,
        maintenance_fee_per_sqft=0.48,
        normalized_maintenance_fee=0.32,
        flood_risk="low",
        feature_tags=[],
        price_fit_score=0.92,
        security_score=0.90,
        transit_proximity_score=0.85,
        floor_level=12,
        facing="north",
        bedrooms=3,
        bathrooms=2,
        url="https://edgeprop.my/mock/pj001",
        source="EdgeProp.my",
        is_mock=True,
    ),
    Property(
        property_id="PJ002",
        title="Subang Jaya Mixed Development",
        price=450000,
        location="Subang Jaya, Selangor",
        administrative_district="subang_jaya",
        distance_to_mrt_km=2.5,
        is_gated_guarded=True,
        security_level="medium",
        facilities=["pool", "gym", "parking"],
        facilities_score=0.80,
        nearby_schools=3,
        nearby_tuition_centers=2,
        nearby_malls=2,
        nearby_clinics=1,
        lifestyle_proximity_score=0.80,
        maintenance_fee_per_sqft=0.42,
        normalized_maintenance_fee=0.28,
        flood_risk="low",
        feature_tags=["far_from_mrt"],
        price_fit_score=0.85,
        security_score=0.80,
        transit_proximity_score=0.70,
        floor_level=10,
        facing="east",
        bedrooms=3,
        bathrooms=2,
        url="https://mudah.my/mock/pj002",
        source="Mudah.my",
        is_mock=True,
    ),
    Property(
        property_id="PJ003",
        title="Damansara Luxury Townhouses",
        price=520000,
        location="Damansara, Selangor",
        administrative_district="damansara",
        distance_to_mrt_km=3.0,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "security"],
        facilities_score=0.92,
        nearby_schools=4,
        nearby_tuition_centers=3,
        nearby_malls=2,
        nearby_clinics=1,
        lifestyle_proximity_score=0.88,
        maintenance_fee_per_sqft=0.52,
        normalized_maintenance_fee=0.38,
        flood_risk="low",
        feature_tags=[],
        price_fit_score=0.90,
        security_score=0.93,
        transit_proximity_score=0.75,
        floor_level=0,
        facing="north",
        bedrooms=4,
        bathrooms=3,
        url="https://propsocial.my/mock/pj003",
        source="PropSocial.my",
        is_mock=True,
    ),

    # Additional properties to reach 40+ count
    Property(
        property_id="JB007",
        title="Green Park Residence @ Johor Bahru",
        price=470000,
        location="Green Park, Johor Bahru",
        administrative_district="johor_bahru_city",
        distance_to_mrt_km=2.2,
        is_gated_guarded=True,
        security_level="high",
        facilities=["pool", "gym", "parking", "playground"],
        facilities_score=0.87,
        nearby_schools=3,
        nearby_tuition_centers=2,
        nearby_malls=2,
        nearby_clinics=1,
        lifestyle_proximity_score=0.82,
        maintenance_fee_per_sqft=0.46,
        normalized_maintenance_fee=0.31,
        flood_risk="low",
        feature_tags=[],
        price_fit_score=0.91,
        security_score=0.89,
        transit_proximity_score=0.83,
        floor_level=11,
        facing="south",
        bedrooms=3,
        bathrooms=2,
        url="https://edgeprop.my/mock/jb007",
        source="EdgeProp.my",
        is_mock=True,
    ),
    Property(
        property_id="JB008",
        title="Lakeside Apartments @ Gelang Patah",
        price=410000,
        location="Gelang Patah, Johor Bahru",
        administrative_district="gelang_patah",
        distance_to_mrt_km=3.5,
        is_gated_guarded=False,
        security_level="medium",
        facilities=["parking", "gym"],
        facilities_score=0.60,
        nearby_schools=1,
        nearby_tuition_centers=1,
        nearby_malls=1,
        nearby_clinics=0,
        lifestyle_proximity_score=0.55,
        maintenance_fee_per_sqft=0.38,
        normalized_maintenance_fee=0.22,
        flood_risk="medium",
        feature_tags=["high_floor", "far_from_school"],
        price_fit_score=0.72,
        security_score=0.65,
        transit_proximity_score=0.55,
        floor_level=17,
        facing="west",
        bedrooms=2,
        bathrooms=1,
        url="https://starproperty.my/mock/jb008",
        source="StarProperty.my",
        is_mock=True,
    ),
    Property(
        property_id="KL006",
        title="Wangsa Maju Contemporary Living",
        price=430000,
        location="Wangsa Maju, Kuala Lumpur",
        administrative_district="wangsa_maju",
        distance_to_mrt_km=2.8,
        is_gated_guarded=True,
        security_level="medium",
        facilities=["pool", "parking"],
        facilities_score=0.72,
        nearby_schools=2,
        nearby_tuition_centers=1,
        nearby_malls=1,
        nearby_clinics=1,
        lifestyle_proximity_score=0.68,
        maintenance_fee_per_sqft=0.41,
        normalized_maintenance_fee=0.26,
        flood_risk="low",
        feature_tags=["no_gym"],
        price_fit_score=0.81,
        security_score=0.76,
        transit_proximity_score=0.68,
        floor_level=9,
        facing="east",
        bedrooms=3,
        bathrooms=2,
        url="https://mudah.my/mock/kl006",
        source="Mudah.my",
        is_mock=True,
    ),
]

def load_mock_data() -> list[Property]:
    """Load all mock properties."""
    return MOCK_PROPERTIES

def get_mock_properties_by_district(district: str) -> list[Property]:
    """Filter mock properties by administrative district."""
    return [p for p in MOCK_PROPERTIES if p.administrative_district == district]

